In [11]:
# HIDDEN
# This useful nonsense should just go at the top of your notebook.
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
import numpy as np
plots.style.use('fivethirtyeight')
# datascience version number of last run of this notebook
version.__version__

'0.5.9'

<h1>Class 5: Variance and Dice</h1>

Let's try to build some intuition for *variance* &mdash; in the sense of *random disturbances*.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/2-Dice-Icon.svg/1024px-2-Dice-Icon.svg.png" align=right valign=top width=160> 

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/2-Dice-Icon.svg/1024px-2-Dice-Icon.svg.png" align=right valign=top width=160>


Imagine you have 4 six-sided dice.  

We could actually roll 4 dice over and over and over again, but we can also *simulate it* using Python. 

When you're playing "craps" in a casino, you roll 2 dice and look at the <b>sum</b>. Using 4 dice instead makes this game a little more interesting, but you'd see a similar story unfold regardless of how many dice you use.

<font color="blue">Q1: What's the "average" or most likely sum of 4 dice rolled at once?</blue>

Hint: Each dice is equally likely to roll 1, 2, 3, 4, 5, or 6, with $\frac{1}{6}$ probability for each outcome. So the average number rolled for one dice equals 

$$\frac{1}{6}\times 1 + \frac{1}{6}\times 2 + ...  = \frac{1}{6}\times \sum_{x=1}^6 x$$

Using this, what's the average sum of 4 such dice?

Let's simulate some random numbers in Python. It took me a while to figure out how to get example what I wanted, but I started with `np.random.random()`. Here is code that generates an array with 3 rows and 4 columns of uniformly distributed random variables:

In [52]:
np.random.random((3, 4))

array([[ 0.70286861,  0.01759089,  0.33288908,  0.68985756],
       [ 0.19656059,  0.33458493,  0.79118112,  0.38131212],
       [ 0.34622238,  0.02968661,  0.43454015,  0.79329015]])

And if we want to sum across a dimension of the array, we can use `np.sum()` where the second argument is the *n*th dimension to sum across. The 0th dimension is rows. The 1st dimension is columns:

In [55]:
np.sum(np.random.random((3, 4)),1)

array([ 1.03704751,  1.81960593,  1.75309453])

It turns out that `np.random.randint(a, b, size)` helpfully generates random draws of integers in the interval [a, b) &mdash; so that it doesn't ever draw b. So passing 1 and 7 to it produces a nice simulation of a six-sided dice. Here is a 10-by-4 matrix of simulated six-sided dice rolls, with each row representing a roll and each column representing one of the dice in the roll:

In [59]:
np.random.randint(1,7,size=(10,4))

array([[3, 6, 1, 3],
       [5, 4, 5, 1],
       [3, 5, 5, 5],
       [6, 6, 4, 3],
       [3, 5, 1, 6],
       [2, 5, 1, 6],
       [1, 4, 4, 3],
       [5, 4, 5, 1],
       [1, 6, 4, 3],
       [5, 2, 4, 4]])

<font color="blue">Q2: Create a 1000-by-4 array of dice rolls.</blue>

In [61]:
Dice = ...
Dice

Ellipsis

<font color="blue">Q3: Collapse `Dice` into a 1000-by-1 array of the sum of 4 dice rolled at once, 1000 times.</blue>

In [63]:
Dicesum = ...
Dicesum

Ellipsis

What have we got? One thousand dice rolls, without getting carpal tunnel syndrome or getting shot by the cowboys at the craps table!

Let's look at a histogram of the sums across the four dice. To pull a histogram, use

`plots.hist(x, bins=y)'

where `x` is your data array (here, `Dicesum`), and `y` is a range of bins you'd like.

Remember that to generate a range of integers from 1 to 25, you can call `np.arange` like this:

In [65]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

You can also trim out the impossible numbers if you'd like, since the minimum sum of four dice is 4.

<font color="blue">Q4: Generate a histogram of your simulation (`Dicesum`).</blue>

In [68]:
...

Ellipsis

<font color="blue">Q5: Do you see the mean sum of dice you calculated in Q1 in the histogram? Where?</blue>

<font color="blue">Q6: Suppose I told you that I saw a dice roll that was four 6's, or a sum of 24. How likely is that outcome?</blue>